### ISSUE TITLE
Unconnected forks to be merged

### ISSUE THREAD

**Issue by quozl** [sugarlabs/GTranslator#8]
Any useful commits from other forks should be merged here, and other forks may be suggested for deletion if not in use.

* https://github.com/sugar-activities/4317-activity - has different metadata; including version, and bundle id is present instead of deprecated service_name,

* https://github.com/Daksh/GTranslator - may be no different, not yet checked.

Suggestions;

* [x] clone other repositories,
* [x] compare each repository, assessing any useful changes,
* [x] prepare patches for changes,
* [x] make a puill request referencing this issue, and wait for merge,
* [x] raise an issue on duplicate repositories.

**Comment by nswarup14** [comment]
@quozl 
I have made attempt at merging the unconnected forks at https://github.com/nswarup14/GTranslator/.

These were the steps I took
1) Cloned the respective repositories
2) Found the activity bundles at http://activities.sugarlabs.org/activities/4317/. Downloaded them and unzipped them.
3) Compared the released to the clones and decided to base it on https://github.com/Daksh/GTranslator as it most closely matched the `v1` bundle.
4) Added `GIT_COMMITTER_DATE="2010-06-30 04:12" git tag v1 HEAD`. I located the time from http://activities.sugarlabs.org/activities/4317/, under 'Last Modified'.
5) Cherry-picked @ezequielpereira work https://github.com/sugarlabs/GTranslator/commit/01910f94b43057252a160d027869004b0d2a3057
6) Added `GIT_COMMITTER_DATE="2016-01-27 17:39" git tag v2 HEAD`, as it most closely resembled the `v2` bundle.

Kindly review. Thanks

**Comment by quozl** [comment]
Thanks, looks fine.  But your clone is unconnected; what do you suggest next?

**Comment by nswarup14** [comment]
@quozl 
Thanks!
We can delete this repository and fork the one I created to `sugarlabs`. Similar to Bichos-activity(https://github.com/sugarlabs/bichos-activity/issues/9)
Please advise

**Comment by quozl** [comment]
No, thanks.  That would lose history of discussion.  Here's what I did;

* cloned this repository,
* created a new branch _prior_ and pushed, `git checkout -b prior`, `git push --set-upstream origin prior`
* added your repository as a remote and fetched your master branch, `git remote add n ...`, `git fetch n`,
* reset _master_ to the head of your _master_, `git reset --hard b2a442e`
* pushed, `git push --force`.

Also to finish off the checklist here, marked the _two_ duplicate repositories with issues;
* https://github.com/nswarup14/GTranslator/issues/1
* https://github.com/Daksh/GTranslator/issues/1
